---
service: buyrite-api

frameworkVersion: '2'

custom:
  dockerizePip: true
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  region: us-east-2

  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-python-requirements
  - serverless-wsgi
